# Generated by Django 3.0.9 on 2020-08-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SortAlgorithms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Algorithm_type', models.IntegerField(choices=[(1, 'Bubble'), (2, 'Insertion'), (3, 'Merge'), (4, 'Qsort')], default=(1, 'Bubble'), verbose_name='Type of algorithm')),
                ('unsorted_numbers', models.FileField(upload_to='documents/')),
                ('sorted_result', models.TextField(verbose_name='result')),
                ('worked_at', models.DateTimeField(auto_now_add=True)),
                ('work_time', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Sort_info',
                'verbose_name_plural': 'Sort_info',
                'ordering': ['-worked_at'],
            },
        ),
    ]
