# Generated by Django 3.0.9 on 2020-08-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsorted_numbers', models.TextField(verbose_name='unsorted_seq')),
                ('sorted_numbers', models.TextField(verbose_name='sorted_seq')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
            },
        ),
    ]
