# Generated by Django 3.0.9 on 2020-08-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortApp', '0003_auto_20200804_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortalgorithms',
            name='test_check',
            field=models.BooleanField(default=False, verbose_name='test_checked'),
        ),
    ]
